<h1>Manage Users</h1>

<div class="list-group">
<?php foreach ($this->users as $user): ?>
  <div class="list-group-item">
    <h4 class="list-group-item-heading">
      <a href="<?= $this->url('user/edit', ['id' => $user['id']]) ?>">
        <?= $user['name'] ?>
      </a>
      <?php if ($user['is_admin']): ?>
        <i class="text-success text-small" style="font-size:13px">Admin</i>
      <?php endif; ?>
    </h4>

    <div class="btn-group" role="group" aria-label="user actions">
      <a class="btn btn-xs btn-default" href="<?= $this->url('user/edit', ['id' => $user['id']]) ?>">Edit</a>
      <a class="btn btn-xs btn-danger" href="<?= $this->url('user/delete', ['id' => $user['id']]) ?>">Delete</a>
    </div>
  </div>
<?php endforeach ?>
</div>

<div class="btn-group" role="group" aria-label="Add actions">
  <a class="btn btn-primary" href="<?= $this->url('user/add') ?>">Add Record</a>
</div>